### ISSUE TITLE
Abstract subreddit list

### ISSUE THREAD

**Issue by Refisio** [RubenJ01/rewrite#16]
As it stands now, the reddit cog contains a constant list of subreddits that can be pulled from to populate the output of the command. This should be alterable though the bot itself instead of having to manually change the list and restart the bot.

- Move subreddit list to an external file
- Add ability to add to this list
- Add ability to remove from this list
- Background task that updates external file every X minutes/seconds
- Command that allows for the list to be updated automagically

**Comment by RohanJnr** [comment]
update what?
like a command to add and remove, update ?

**Comment by Refisio** [comment]
A command would be a direct interface, and probably the best method for this type of action.

**Comment by RubenJ01** [comment]
This would be a command for only the devs i suppose?
Or where you thinking that admins in a server can expand the list theirselves, in that case, each server will end up with a different list of subreddits.

**Comment by RohanJnr** [comment]
I will do this one.
