### ISSUE TITLE
Activity Tracker

### ISSUE THREAD

**Issue by RubenJ01** [RubenJ01/rewrite#37]
Track how much times each command has been used so we can see the activity arround the bot.

Call to this list with an admin only command that shows a list like so;
-;reddit {uses}
.....etc

**Comment by RohanJnr** [comment]
Havent got many ideas for this but i think we can use the event "on_message"

**Comment by RohanJnr** [comment]
nvm, we can use on_command event
I will do this one.

**Comment by RohanJnr** [comment]
closing this and this is done.
