### ISSUE TITLE
Adding Lairs to monster statblock list

### ISSUE THREAD

**Issue by theoriginalblackmage** [RubenJ01/rewrite#38]
At the moment while the monster blocks are being added in, or reworked, a addition to the list that has a few options as to the HOW of adding is lairs for monster that have it as a option. The stat blocks would be relatively simple, as there are less than a half dozen options, that go off Once a round on initiative 20, going last in the event of a tie. 

Since you already have the command 
.monster adult dragon

you could add the lair in as 
.monster adult gold dragon lair

for dragons you would also need a dual alias as BOTH adult and ancient dragons of metallic and chromatic colors get lairs, the options do not change for either. 

You could also cut the prefix name alias off and make it like the rest for the dragon section of lairs.
.monster gold dragon lair
.monster white dragon lair
.monster lich lair

Another option is since you have split the statblocks up into multiple pages within the same post for a given creature that has a lot of information you can simply add in the lair action as a section that goes after the legendary action section of the creature. 

It would expand the number of pages for a creature, but you also have reaction role emoji's for going between the pages and not needing separate commands beyond the initial pull command for going between the pages. You also benefit from the fact of staying with the just the base SRD and MM list of creatures, there are relatively few that have their own lairs, and environmental and combat actions on top of the creature itself, so the list is easy to compile and input. This would also give you something that no other D&D has, a function to look up and add lairs to the requisite creature as well as a possibility of adding the lairs to the encounter builder with a simple "(lair)" added to a creature where applicable. So, Adult White Dragon, Adult White Dragon (Lair, or with lair) in the pull for a given encounter build.

**Comment by RubenJ01** [comment]
It appears that the srd database makes no difference, or doesn't contain monster in lair.
For example, the `adult gold dragon` exists in our database but the `adult gold dragon lair` does not exist.
This is either missing or its non SRD content.
