### ISSUE TITLE
KeyError raised on specific SRD entries.

### ISSUE THREAD

**Issue by Refisio** [RubenJ01/rewrite#47]
A key error is raised when certain entries of the SRD are called upon. The following spreadsheet contains a list of those entries.

https://docs.google.com/spreadsheets/d/138Cj5a0WMC_AQTLYBgYmRFRYx-7yZ_2N6gSBJQtOCc4/edit#gid=0

**Comment by RubenJ01** [comment]
Il take a look at this.
